### ISSUE TITLE
Question on adding custom CSS to tooltips. 

### ISSUE THREAD

**Issue by yanislavzagorov** [highcharts/highcharts-react#242]
I'm trying to do some funky styling for the labels on one of my bar charts. To do so I changed the tooltips to html elements instead of svg images by setting:

```javascript
tooltip: {
    useHTML: true
},
```

and now I would like to apply the following CSS rules:

```css
.highcharts-tooltip span {
    font-size: 13px;
    text-overflow: none;
    word-break: break-all;
}
```

I tried creating a separate CSS file to do so, but that did not seem to work. I couldn't add the stylings into my material-ui makeStyles declaration. 

What would be the correct way of adding a css rule like this to highcharts-react?
